name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  # Build package and increase version
  build-version:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          ref: main
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      # Ensure that the README is published with the package
      - name: Set new version from release tag
        run: |
          git config user.name "Nahuel Alejandro Ramos"
          git config user.email "nahuel@checklyhq.com"
          npm --no-git-tag-version version ${{ github.event.release.tag_name }}
          git add .
      - name: Append changes to changelog
        run: |
          npx auto-changelog --latest-version ${{ github.event.release.tag_name }}
          git add .
      - name: Git push new package version
        run: |
          git commit -m "feat: release CLI ${{ github.event.release.tag_name }}"
          git push origin main --follow-tags
      - name: Output version change after push
        run: npm pkg get version
  # Publish package to NPM
  publish:
    runs-on: ubuntu-latest
    environment: production
    needs: build-version
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      # Ensure that the README is published with the package
      - name: Publish NPM package
        run: npm pkg get version
